// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/raftkv/raftkv.proto

package raftkv

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifyRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ea5a993eb3bfe7, []int{0}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type VerifyResponse struct {
	RootDigest            []byte   `protobuf:"bytes,1,opt,name=root_digest,json=rootDigest,proto3" json:"root_digest,omitempty"`
	SideNodes             [][]byte `protobuf:"bytes,2,rep,name=side_nodes,json=sideNodes,proto3" json:"side_nodes,omitempty"`
	NonMembershipLeafData []byte   `protobuf:"bytes,3,opt,name=non_membership_leaf_data,json=nonMembershipLeafData,proto3" json:"non_membership_leaf_data,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *VerifyResponse) Reset()         { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()    {}
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ea5a993eb3bfe7, []int{1}
}

func (m *VerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResponse.Unmarshal(m, b)
}
func (m *VerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResponse.Marshal(b, m, deterministic)
}
func (m *VerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResponse.Merge(m, src)
}
func (m *VerifyResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyResponse.Size(m)
}
func (m *VerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResponse proto.InternalMessageInfo

func (m *VerifyResponse) GetRootDigest() []byte {
	if m != nil {
		return m.RootDigest
	}
	return nil
}

func (m *VerifyResponse) GetSideNodes() [][]byte {
	if m != nil {
		return m.SideNodes
	}
	return nil
}

func (m *VerifyResponse) GetNonMembershipLeafData() []byte {
	if m != nil {
		return m.NonMembershipLeafData
	}
	return nil
}

type SetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ea5a993eb3bfe7, []int{2}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ea5a993eb3bfe7, []int{3}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

type Block struct {
	Reqs                 []*SetRequest `protobuf:"bytes,1,rep,name=reqs,proto3" json:"reqs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ea5a993eb3bfe7, []int{4}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetReqs() []*SetRequest {
	if m != nil {
		return m.Reqs
	}
	return nil
}

type JoinRequest struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PeerAddr             string   `protobuf:"bytes,2,opt,name=peer_addr,json=peerAddr,proto3" json:"peer_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ea5a993eb3bfe7, []int{5}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *JoinRequest) GetPeerAddr() string {
	if m != nil {
		return m.PeerAddr
	}
	return ""
}

type JoinResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ea5a993eb3bfe7, []int{6}
}

func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (m *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(m, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

type LeaveRequest struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRequest) Reset()         { *m = LeaveRequest{} }
func (m *LeaveRequest) String() string { return proto.CompactTextString(m) }
func (*LeaveRequest) ProtoMessage()    {}
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ea5a993eb3bfe7, []int{7}
}

func (m *LeaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRequest.Unmarshal(m, b)
}
func (m *LeaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRequest.Marshal(b, m, deterministic)
}
func (m *LeaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRequest.Merge(m, src)
}
func (m *LeaveRequest) XXX_Size() int {
	return xxx_messageInfo_LeaveRequest.Size(m)
}
func (m *LeaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRequest proto.InternalMessageInfo

func (m *LeaveRequest) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

type LeaveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveResponse) Reset()         { *m = LeaveResponse{} }
func (m *LeaveResponse) String() string { return proto.CompactTextString(m) }
func (*LeaveResponse) ProtoMessage()    {}
func (*LeaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ea5a993eb3bfe7, []int{8}
}

func (m *LeaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveResponse.Unmarshal(m, b)
}
func (m *LeaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveResponse.Marshal(b, m, deterministic)
}
func (m *LeaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveResponse.Merge(m, src)
}
func (m *LeaveResponse) XXX_Size() int {
	return xxx_messageInfo_LeaveResponse.Size(m)
}
func (m *LeaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveResponse proto.InternalMessageInfo

type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ea5a993eb3bfe7, []int{9}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ea5a993eb3bfe7, []int{10}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type IsLeaderRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsLeaderRequest) Reset()         { *m = IsLeaderRequest{} }
func (m *IsLeaderRequest) String() string { return proto.CompactTextString(m) }
func (*IsLeaderRequest) ProtoMessage()    {}
func (*IsLeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ea5a993eb3bfe7, []int{11}
}

func (m *IsLeaderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsLeaderRequest.Unmarshal(m, b)
}
func (m *IsLeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsLeaderRequest.Marshal(b, m, deterministic)
}
func (m *IsLeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsLeaderRequest.Merge(m, src)
}
func (m *IsLeaderRequest) XXX_Size() int {
	return xxx_messageInfo_IsLeaderRequest.Size(m)
}
func (m *IsLeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsLeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsLeaderRequest proto.InternalMessageInfo

type IsLeaderResponse struct {
	IsLeader             bool     `protobuf:"varint,1,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsLeaderResponse) Reset()         { *m = IsLeaderResponse{} }
func (m *IsLeaderResponse) String() string { return proto.CompactTextString(m) }
func (*IsLeaderResponse) ProtoMessage()    {}
func (*IsLeaderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ea5a993eb3bfe7, []int{12}
}

func (m *IsLeaderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsLeaderResponse.Unmarshal(m, b)
}
func (m *IsLeaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsLeaderResponse.Marshal(b, m, deterministic)
}
func (m *IsLeaderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsLeaderResponse.Merge(m, src)
}
func (m *IsLeaderResponse) XXX_Size() int {
	return xxx_messageInfo_IsLeaderResponse.Size(m)
}
func (m *IsLeaderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsLeaderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsLeaderResponse proto.InternalMessageInfo

func (m *IsLeaderResponse) GetIsLeader() bool {
	if m != nil {
		return m.IsLeader
	}
	return false
}

type KVItem struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVItem) Reset()         { *m = KVItem{} }
func (m *KVItem) String() string { return proto.CompactTextString(m) }
func (*KVItem) ProtoMessage()    {}
func (*KVItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_91ea5a993eb3bfe7, []int{13}
}

func (m *KVItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVItem.Unmarshal(m, b)
}
func (m *KVItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVItem.Marshal(b, m, deterministic)
}
func (m *KVItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVItem.Merge(m, src)
}
func (m *KVItem) XXX_Size() int {
	return xxx_messageInfo_KVItem.Size(m)
}
func (m *KVItem) XXX_DiscardUnknown() {
	xxx_messageInfo_KVItem.DiscardUnknown(m)
}

var xxx_messageInfo_KVItem proto.InternalMessageInfo

func (m *KVItem) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KVItem) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*VerifyRequest)(nil), "kv.VerifyRequest")
	proto.RegisterType((*VerifyResponse)(nil), "kv.VerifyResponse")
	proto.RegisterType((*SetRequest)(nil), "kv.SetRequest")
	proto.RegisterType((*SetResponse)(nil), "kv.SetResponse")
	proto.RegisterType((*Block)(nil), "kv.Block")
	proto.RegisterType((*JoinRequest)(nil), "kv.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "kv.JoinResponse")
	proto.RegisterType((*LeaveRequest)(nil), "kv.LeaveRequest")
	proto.RegisterType((*LeaveResponse)(nil), "kv.LeaveResponse")
	proto.RegisterType((*GetRequest)(nil), "kv.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "kv.GetResponse")
	proto.RegisterType((*IsLeaderRequest)(nil), "kv.IsLeaderRequest")
	proto.RegisterType((*IsLeaderResponse)(nil), "kv.IsLeaderResponse")
	proto.RegisterType((*KVItem)(nil), "kv.KVItem")
}

func init() { proto.RegisterFile("proto/raftkv/raftkv.proto", fileDescriptor_91ea5a993eb3bfe7) }

var fileDescriptor_91ea5a993eb3bfe7 = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x95, 0xb8, 0x0d, 0xc9, 0xc4, 0xf9, 0x5a, 0x8a, 0x30, 0xae, 0x80, 0xb0, 0x48, 0x25,
	0x08, 0x94, 0xa0, 0x02, 0xe2, 0x4c, 0x88, 0x14, 0x05, 0x02, 0x07, 0x57, 0xea, 0x81, 0x8b, 0xb5,
	0x65, 0x27, 0x60, 0x39, 0xf1, 0xa6, 0xbb, 0x5b, 0x4b, 0x7d, 0x04, 0x1e, 0x80, 0xf7, 0x45, 0xbb,
	0xde, 0xd4, 0x6e, 0xc4, 0xc7, 0x29, 0x99, 0xdf, 0xfc, 0xe7, 0x63, 0x67, 0xc6, 0xf0, 0x60, 0x2b,
	0x85, 0x16, 0x13, 0xc9, 0x56, 0x3a, 0xcd, 0xdd, 0xcf, 0xd8, 0x32, 0x52, 0x4f, 0x73, 0xfa, 0x04,
	0x3a, 0xe7, 0x28, 0x93, 0xd5, 0x75, 0x84, 0x97, 0x57, 0xa8, 0x34, 0xe9, 0x83, 0x97, 0xe2, 0x75,
	0x50, 0x1b, 0xd6, 0x46, 0xad, 0xc8, 0xfc, 0xa5, 0x3f, 0x6b, 0xd0, 0xdd, 0x69, 0xd4, 0x56, 0x64,
	0x0a, 0xc9, 0x63, 0x68, 0x4b, 0x21, 0x74, 0xcc, 0x93, 0xef, 0xa8, 0xb4, 0x15, 0xfb, 0x11, 0x18,
	0x34, 0xb3, 0x84, 0x3c, 0x04, 0x50, 0x09, 0xc7, 0x38, 0x13, 0x1c, 0x55, 0x50, 0x1f, 0x7a, 0x23,
	0x3f, 0x6a, 0x19, 0xf2, 0xc5, 0x00, 0xf2, 0x0e, 0x82, 0x4c, 0x64, 0xf1, 0x06, 0x37, 0x17, 0x28,
	0xd5, 0x8f, 0x64, 0x1b, 0xaf, 0x91, 0xad, 0x62, 0xce, 0x34, 0x0b, 0x3c, 0x9b, 0xec, 0x5e, 0x26,
	0xb2, 0xcf, 0x37, 0xee, 0x25, 0xb2, 0xd5, 0x8c, 0x69, 0x46, 0xdf, 0x00, 0x9c, 0xa1, 0xfe, 0x6b,
	0xaf, 0xe4, 0x08, 0x0e, 0x73, 0xb6, 0xbe, 0xc2, 0xa0, 0x6e, 0x59, 0x61, 0xd0, 0x0e, 0xb4, 0x6d,
	0x54, 0xd1, 0x3d, 0x7d, 0x01, 0x87, 0xd3, 0xb5, 0xf8, 0x96, 0x12, 0x0a, 0x07, 0x12, 0x2f, 0x55,
	0x50, 0x1b, 0x7a, 0xa3, 0xf6, 0x69, 0x77, 0x9c, 0xe6, 0xe3, 0x32, 0x7b, 0x64, 0x7d, 0xf4, 0x03,
	0xb4, 0x3f, 0x8a, 0x24, 0xdb, 0x95, 0xbc, 0x0f, 0x77, 0xb6, 0x88, 0x32, 0x4e, 0xb8, 0x2b, 0xdb,
	0x30, 0xe6, 0x82, 0x93, 0x63, 0x68, 0x59, 0x07, 0xe3, 0x5c, 0xba, 0xea, 0x4d, 0x03, 0xde, 0x73,
	0x2e, 0x69, 0x17, 0xfc, 0x22, 0x89, 0xeb, 0xe0, 0x19, 0xf8, 0x4b, 0x64, 0x39, 0xfe, 0x2f, 0x2b,
	0xed, 0x41, 0xc7, 0x09, 0x5d, 0xe4, 0x23, 0x80, 0xf9, 0x3f, 0x06, 0x40, 0x9f, 0x42, 0x7b, 0x5e,
	0x3e, 0xb5, 0x9c, 0x47, 0xad, 0x3a, 0x8f, 0x01, 0xf4, 0x16, 0x6a, 0x89, 0x8c, 0xa3, 0x74, 0x99,
	0xe8, 0x04, 0xfa, 0x25, 0x72, 0xc1, 0xc7, 0xd0, 0x4a, 0x94, 0xd9, 0x0c, 0x47, 0x69, 0x13, 0x34,
	0xa3, 0x66, 0xe2, 0x44, 0xf4, 0x15, 0x34, 0x3e, 0x9d, 0x2f, 0x34, 0x6e, 0xaa, 0x4d, 0xf8, 0x7f,
	0xd8, 0x82, 0xef, 0xaa, 0x9e, 0xfe, 0xaa, 0x43, 0x7d, 0x36, 0x25, 0x27, 0xe0, 0x9d, 0xa1, 0x26,
	0x7b, 0xd3, 0x0e, 0x7b, 0x37, 0xb6, 0xab, 0x7e, 0x02, 0xde, 0x7c, 0xa7, 0x9b, 0xef, 0xe9, 0xaa,
	0x4f, 0x9c, 0x40, 0xa3, 0xb8, 0x4e, 0x32, 0x30, 0xae, 0x5b, 0xd7, 0x1c, 0x92, 0x2a, 0x72, 0x01,
	0x6f, 0xa1, 0xb9, 0x7b, 0x2a, 0xb9, 0x6b, 0xfc, 0x7b, 0xb3, 0x08, 0x8f, 0x6e, 0x43, 0x17, 0xf6,
	0x1c, 0x0e, 0xcc, 0x0e, 0x89, 0x6d, 0xa0, 0x72, 0x12, 0x61, 0xbf, 0x04, 0x4e, 0xfa, 0x12, 0x0e,
	0xed, 0xd6, 0x88, 0x75, 0x55, 0x37, 0x1d, 0x0e, 0x2a, 0xa4, 0x50, 0x4f, 0xbb, 0x5f, 0xfd, 0xea,
	0x37, 0x7a, 0xd1, 0xb0, 0xd6, 0xeb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xab, 0x80, 0x95,
	0xba, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DBClient is the client API for DB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DBClient interface {
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	IsLeader(ctx context.Context, in *IsLeaderRequest, opts ...grpc.CallOption) (*IsLeaderResponse, error)
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error)
}

type dBClient struct {
	cc *grpc.ClientConn
}

func NewDBClient(cc *grpc.ClientConn) DBClient {
	return &dBClient{cc}
}

func (c *dBClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/kv.DB/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/kv.DB/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, "/kv.DB/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) IsLeader(ctx context.Context, in *IsLeaderRequest, opts ...grpc.CallOption) (*IsLeaderResponse, error) {
	out := new(IsLeaderResponse)
	err := c.cc.Invoke(ctx, "/kv.DB/IsLeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, "/kv.DB/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error) {
	out := new(LeaveResponse)
	err := c.cc.Invoke(ctx, "/kv.DB/Leave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBServer is the server API for DB service.
type DBServer interface {
	Set(context.Context, *SetRequest) (*SetResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	IsLeader(context.Context, *IsLeaderRequest) (*IsLeaderResponse, error)
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	Leave(context.Context, *LeaveRequest) (*LeaveResponse, error)
}

// UnimplementedDBServer can be embedded to have forward compatible implementations.
type UnimplementedDBServer struct {
}

func (*UnimplementedDBServer) Set(ctx context.Context, req *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedDBServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedDBServer) Verify(ctx context.Context, req *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (*UnimplementedDBServer) IsLeader(ctx context.Context, req *IsLeaderRequest) (*IsLeaderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsLeader not implemented")
}
func (*UnimplementedDBServer) Join(ctx context.Context, req *JoinRequest) (*JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedDBServer) Leave(ctx context.Context, req *LeaveRequest) (*LeaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}

func RegisterDBServer(s *grpc.Server, srv DBServer) {
	s.RegisterService(&_DB_serviceDesc, srv)
}

func _DB_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.DB/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.DB/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.DB/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_IsLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).IsLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.DB/IsLeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).IsLeader(ctx, req.(*IsLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.DB/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kv.DB/Leave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Leave(ctx, req.(*LeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kv.DB",
	HandlerType: (*DBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _DB_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DB_Get_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _DB_Verify_Handler,
		},
		{
			MethodName: "IsLeader",
			Handler:    _DB_IsLeader_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _DB_Join_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _DB_Leave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/raftkv/raftkv.proto",
}
